# Generated by Django 4.2.7 on 2024-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='exchange',
            field=models.CharField(default='NASDAQ', max_length=100),
            preserve_default=False,
        ),
    ]
