# Generated by Django 4.2.7 on 2024-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_auto_20240122_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
